#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : breathe
Version  : 4.12.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/83/d4/df98c034bccbd1d3ccbbc51100eaeba7f627aef4dfafcdabdcb748589e84/breathe-4.12.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/83/d4/df98c034bccbd1d3ccbbc51100eaeba7f627aef4dfafcdabdcb748589e84/breathe-4.12.0.tar.gz
Summary  : Sphinx Doxygen renderer
Group    : Development/Tools
License  : BSD-3-Clause
Requires: breathe-bin = %{version}-%{release}
Requires: breathe-python = %{version}-%{release}
Requires: breathe-python3 = %{version}-%{release}
Requires: Sphinx
Requires: docutils
Requires: six
BuildRequires : buildreq-distutils3

%description
Breathe
=======
.. image:: https://travis-ci.org/michaeljones/breathe.svg?branch=master
:target: https://travis-ci.org/michaeljones/breathe

%package bin
Summary: bin components for the breathe package.
Group: Binaries

%description bin
bin components for the breathe package.


%package python
Summary: python components for the breathe package.
Group: Default
Requires: breathe-python3 = %{version}-%{release}

%description python
python components for the breathe package.


%package python3
Summary: python3 components for the breathe package.
Group: Default
Requires: python3-core

%description python3
python3 components for the breathe package.


%prep
%setup -q -n breathe-4.12.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554742442
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/breathe-apidoc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
